apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thelounge
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: thelounge
    server: {{ .Values.spec.destination.server }}
  sources:
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: {{ .Values.spec.source.ref }}
    - repoURL: https://geek-cookbook.github.io/charts/
      targetRevision: "3.4.2"
      chart: thelounge
      helm:
        valueFiles:
          - $values_repo/charts/thelounge/values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
